server:
  port: 9060
  servlet:
    context-path: /api/ventas

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ventas
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults:
        dialect: org.hibernate.dialect.PostgresPlusDialect

